language: node_js
node_js: stable

before_script:
  - git config --global user.name "Honye"
  - git config --global user.email "hongye.jun@qq.com"
  - chmod +x ./deploy.sh  # 为 shell 文件添加可执行权限

install:
  - npm install yarn -g
  - yarn

script:
  - yarn build

after_script:
  - ./deploy.sh

branches:
  only:
    - vuepress
cache:
  directories:
    - node_modules

env:
  global:
    - GITHUB_REF: github.com/Honye/notes.git

# deploy:
#   provider: pages
#   skip-cleanup: true
#   local_dir: .vuepress/dist
#   github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
#   keep-history: true
#   on:
#     branch: vuepress